name = "GenuineZeroUniformAtlasEnergy"
version = "0.2.0"
defaultTargets = ["GenuineZeroUniformAtlasEnergy"]

[[lean_lib]]
name = "GenuineZeroUniformAtlasEnergy"

[[require]]
name = "CPFormal"
git = "https://github.com/thiagomassensini/primos.git"
rev = "0c64a8366ded96a3242cbe0888c55144442c570b"
