import GenuineZeroUniformAtlasEnergy

/-!
# Ordered kernel dependency audit

One `#print axioms` command is recorded for every public theorem introduced by
this repository.  CI checks this order against the theorem registry.
-/

#print axioms GenuineZeroUniformAtlasEnergy.quadraticCarryShell_energy_eq_mass_iff
#print axioms GenuineZeroUniformAtlasEnergy.nativeParameter_re
#print axioms GenuineZeroUniformAtlasEnergy.nativeParameter_im
#print axioms GenuineZeroUniformAtlasEnergy.nativeParameter_mem_genuineCriticalStrip
#print axioms GenuineZeroUniformAtlasEnergy.nativeAmplitude_energy_eq_inverseCarryMass
#print axioms GenuineZeroUniformAtlasEnergy.packagedNativeFiniteChart_eq_genuineFiniteChart
#print axioms GenuineZeroUniformAtlasEnergy.nativeZero_iff_genuineZero
#print axioms GenuineZeroUniformAtlasEnergy.nativeAtlasEnergy_eq_zero
#print axioms GenuineZeroUniformAtlasEnergy.uniformAtlasEnergyBudget_nonneg
#print axioms GenuineZeroUniformAtlasEnergy.isUniformAtlasEnergyBudget_iff_nonneg
#print axioms GenuineZeroUniformAtlasEnergy.zero_isOptimalAtlasEnergyBudget
#print axioms GenuineZeroUniformAtlasEnergy.optimalAtlasEnergyBudget_unique
#print axioms GenuineZeroUniformAtlasEnergy.isOptimalAtlasEnergyBudget_iff_eq_zero
#print axioms GenuineZeroUniformAtlasEnergy.existsUnique_optimalAtlasEnergyBudget
#print axioms GenuineZeroUniformAtlasEnergy.finiteTiltedCenter_eq_radialDifference_mul_pairing
#print axioms GenuineZeroUniformAtlasEnergy.finiteTiltedCenter_eq_zero_iff_re_eq_half
#print axioms GenuineZeroUniformAtlasEnergy.finiteTiltedCenter_eq_zero_iff_carryTilt_eq_zero
#print axioms GenuineZeroUniformAtlasEnergy.finiteTiltedCenter_eq_zero_iff_quadraticBranchDefect_eq_zero
#print axioms GenuineZeroUniformAtlasEnergy.finiteTiltedCenter_ne_zero_of_carryTilt_ne_zero
#print axioms GenuineZeroUniformAtlasEnergy.totalFlux_closes_iff_carryTilt_balanced_at_commonZero
#print axioms GenuineZeroUniformAtlasEnergy.nativeGenuineZero_telescopes_boundary_and_balances_tiltedCenter
#print axioms GenuineZeroUniformAtlasEnergy.genuineZero_offEquilibrium_telescopes_boundary_and_exposes_tiltedCenter
#print axioms GenuineZeroUniformAtlasEnergy.genuineZero_hasUniqueUniformAtlasEnergyBudget
#print axioms GenuineZeroUniformAtlasEnergy.nativeZero_hasUniqueUniformAtlasEnergyBudget
#print axioms GenuineZeroUniformAtlasEnergy.zeroIdentity_with_uniqueUniformAtlasEnergyBudget
#print axioms GenuineZeroUniformAtlasEnergy.transverseHessian_trace_det_and_positiveDefinite
#print axioms GenuineZeroUniformAtlasEnergy.transverseHessian_eigenvalue_pair
#print axioms GenuineZeroUniformAtlasEnergy.transverseEnvelope_slope_and_curvature
#print axioms GenuineZeroUniformAtlasEnergy.transverseLocalCoercivity_certificate
#print axioms GenuineZeroUniformAtlasEnergy.exactZero_transverse_geometry
#print axioms GenuineZeroUniformAtlasEnergy.transverseCertificateResidual_nonneg_iff
#print axioms GenuineZeroUniformAtlasEnergy.transverseCoercivity_excludes_offCritical_zero
