import GenuineZeroUniformAtlasEnergy.TransverseSpectrum
import CPFormal.Analytic.CpGenuineNativeRealBoundaryCrosswalk
import CPFormal.Analytic.CpBracketHolomorphic
import Mathlib.Analysis.Complex.RealDeriv

/-!
# Concrete finite native transverse bridge

This module connects the abstract transverse jet to the finite primitive
carry camera already defined in `CPFormal`.

For an odd prime camera `p` and cutoff `M`, the complex characteristic is the
finite bracketed Dirichlet chart

```math
\Chi_{p,M}(s)=\mathrm{FiniteChart}_{p,M}(n\mapsto n^{-s}).
```

The upstream real/complex crosswalk proves that, at
`s = sigma + i time`, this is exactly the additive packaging of the primitive
real-plane camera `nativeCarryRealPlaneFiniteChartAt p M sigma time`.

The finite chart is entire.  Restricting it to the real `(sigma,time)` plane
gives the exact tangent relation

```math
\partial_{time}\Chi_{p,M}=i\,\partial_{sigma}\Chi_{p,M}.
```

The multiplication by `i` is then unpacked as the real quarter-turn
`J(x,y)=(-y,x)`.  No zero hypothesis, score normalization, or cutoff limit is
used.
-/

open scoped BigOperators

namespace GenuineZeroUniformAtlasEnergy

open CPFormal.Analytic.Cp
open CPFormal.Genuine.Cp

noncomputable section

/-- The finite complex characteristic before choosing real coordinates. -/
def finiteNativeCharacteristic (p M : ℕ) (s : ℂ) : ℂ :=
  finiteBracketedDirichletChart p M s

/-- The same characteristic on the real radial/time plane. -/
def finiteNativeSlice
    (p M : ℕ) (sigma time : ℝ) : ℂ :=
  finiteNativeCharacteristic p M
    (nativeCarryRealPlaneParameter sigma time)

/-- Complex derivative of the finite characteristic. -/
def finiteNativeFirstJet (p M : ℕ) (s : ℂ) : ℂ :=
  deriv (finiteNativeCharacteristic p M) s

/-- Forget complex multiplication and retain the two real coordinates. -/
def complexToNativePlane (z : ℂ) : NativeCarryRealPlane :=
  (z.re, z.im)

/-- The real quarter-turn generated by the angular clock. -/
def nativeQuarterTurn (u : NativeCarryRealPlane) : NativeCarryRealPlane :=
  (-u.2, u.1)

/-- Euclidean pairing on the native real plane. -/
def nativePlaneInner
    (u v : NativeCarryRealPlane) : ℝ :=
  u.1 * v.1 + u.2 * v.2

/-- The concrete radial tangent of the finite camera. -/
def finiteNativeSigmaTangent
    (p M : ℕ) (sigma time : ℝ) : NativeCarryRealPlane :=
  complexToNativePlane
    (finiteNativeFirstJet p M
      (nativeCarryRealPlaneParameter sigma time))

/-- The concrete angular tangent, written in real coordinates. -/
def finiteNativeTimeTangent
    (p M : ℕ) (sigma time : ℝ) : NativeCarryRealPlane :=
  complexToNativePlane
    (Complex.I * finiteNativeFirstJet p M
      (nativeCarryRealPlaneParameter sigma time))

/-- The finite complex characteristic is exactly the packaged primitive real
camera. -/
theorem finiteNativeSlice_eq_packaged_realCamera
    (p M : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (sigma time : ℝ) :
    finiteNativeSlice p M sigma time =
      nativeCarryRealPlaneComplexPackaging
        (nativeCarryRealPlaneFiniteChartAt p M sigma time) := by
  rw [finiteNativeSlice, finiteNativeCharacteristic,
    finiteBracketedDirichletChart_eq_finiteChart p M hp hpodd]
  exact
    (nativeCarryRealPlaneComplexPackaging_finiteChartAt_eq_dirichlet
      p M hp hpodd sigma time).symm

/-- Every finite native characteristic is entire in its complex parameter. -/
lemma finiteNativeCharacteristic_differentiable
    (p M : ℕ) (hp : Nat.Prime p) :
    Differentiable ℂ (finiteNativeCharacteristic p M) := by
  classical
  unfold finiteNativeCharacteristic finiteBracketedDirichletChart
  exact
    (differentiable_seedSum_dirichletTerm p).add
      (Differentiable.fun_sum fun k _hk =>
        differentiable_realCpSaturatedBracket p k hp)

/-- Varying the real coordinate changes `sigma+i time` with derivative `1`. -/
lemma nativeParameter_hasDerivAt_sigma
    (sigma time : ℝ) :
    HasDerivAt
      (fun x : ℝ => nativeCarryRealPlaneParameter x time)
      (1 : ℂ) sigma := by
  have h :
      HasDerivAt
        (fun x : ℝ => (x : ℂ) + (time : ℂ) * Complex.I)
        (1 : ℂ) sigma := by
    simpa using Complex.ofRealCLM.hasDerivAt.add_const
      ((time : ℂ) * Complex.I)
  convert h using 1 <;>
    ext <;> simp [nativeCarryRealPlaneParameter]

/-- Varying time changes `sigma+i time` with derivative `i`. -/
lemma nativeParameter_hasDerivAt_time
    (sigma time : ℝ) :
    HasDerivAt
      (fun y : ℝ => nativeCarryRealPlaneParameter sigma y)
      Complex.I time := by
  have h :
      HasDerivAt
        (fun y : ℝ => (sigma : ℂ) + (y : ℂ) * Complex.I)
        Complex.I time := by
    simpa using
      (Complex.ofRealCLM.hasDerivAt.mul_const Complex.I).const_add
        (sigma : ℂ)
  convert h using 1 <;>
    ext <;> simp [nativeCarryRealPlaneParameter]

/-- Exact radial derivative of the concrete finite characteristic. -/
lemma finiteNativeSlice_hasDerivAt_sigma
    (p M : ℕ) (hp : Nat.Prime p)
    (sigma time : ℝ) :
    HasDerivAt
      (fun x : ℝ => finiteNativeSlice p M x time)
      (finiteNativeFirstJet p M
        (nativeCarryRealPlaneParameter sigma time)) sigma := by
  have houter :
      HasDerivAt
        (finiteNativeCharacteristic p M)
        (finiteNativeFirstJet p M
          (nativeCarryRealPlaneParameter sigma time))
        (nativeCarryRealPlaneParameter sigma time) :=
    (finiteNativeCharacteristic_differentiable p M hp
      (nativeCarryRealPlaneParameter sigma time)).hasDerivAt
  have hreal := houter.complexToReal_fderiv.comp_hasDerivAt sigma
    (nativeParameter_hasDerivAt_sigma sigma time)
  simpa [finiteNativeSlice] using hreal

/-- Exact angular derivative of the concrete finite characteristic. -/
lemma finiteNativeSlice_hasDerivAt_time
    (p M : ℕ) (hp : Nat.Prime p)
    (sigma time : ℝ) :
    HasDerivAt
      (fun y : ℝ => finiteNativeSlice p M sigma y)
      (Complex.I * finiteNativeFirstJet p M
        (nativeCarryRealPlaneParameter sigma time)) time := by
  have houter :
      HasDerivAt
        (finiteNativeCharacteristic p M)
        (finiteNativeFirstJet p M
          (nativeCarryRealPlaneParameter sigma time))
        (nativeCarryRealPlaneParameter sigma time) :=
    (finiteNativeCharacteristic_differentiable p M hp
      (nativeCarryRealPlaneParameter sigma time)).hasDerivAt
  have hreal := houter.complexToReal_fderiv.comp_hasDerivAt time
    (nativeParameter_hasDerivAt_time sigma time)
  simpa [finiteNativeSlice, mul_comm] using hreal

/-- Multiplication by `i` is exactly the real quarter-turn. -/
@[simp] lemma complexToNativePlane_I_mul (z : ℂ) :
    complexToNativePlane (Complex.I * z) =
      nativeQuarterTurn (complexToNativePlane z) := by
  ext <;> simp [complexToNativePlane, nativeQuarterTurn]

/-- The clock tangent is the quarter-turn of the radial tangent. -/
@[simp] lemma finiteNativeTimeTangent_eq_quarterTurn
    (p M : ℕ) (sigma time : ℝ) :
    finiteNativeTimeTangent p M sigma time =
      nativeQuarterTurn
        (finiteNativeSigmaTangent p M sigma time) := by
  simp [finiteNativeTimeTangent, finiteNativeSigmaTangent]

/-- The quarter-turn preserves the Euclidean quadratic form. -/
@[simp] lemma nativePlaneInner_quarterTurn_self
    (u : NativeCarryRealPlane) :
    nativePlaneInner (nativeQuarterTurn u) (nativeQuarterTurn u) =
      nativePlaneInner u u := by
  rcases u with ⟨x, y⟩
  simp [nativePlaneInner, nativeQuarterTurn]
  ring

/-- Radial and angular tangents are orthogonal in the real plane. -/
@[simp] lemma nativePlaneInner_self_quarterTurn
    (u : NativeCarryRealPlane) :
    nativePlaneInner u (nativeQuarterTurn u) = 0 := by
  rcases u with ⟨x, y⟩
  simp [nativePlaneInner, nativeQuarterTurn]
  ring

/-- Concrete finite Cauchy--Riemann capstone: the primitive real camera is the
finite Dirichlet characteristic, its time derivative is the real quarter-turn
of its sigma derivative, and the two tangent directions have equal norm and
zero pairing. -/
theorem finiteNativeCamera_transverse_tangent_geometry
    (p M : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (sigma time : ℝ) :
    finiteNativeSlice p M sigma time =
        nativeCarryRealPlaneComplexPackaging
          (nativeCarryRealPlaneFiniteChartAt p M sigma time) ∧
      HasDerivAt
        (fun x : ℝ => finiteNativeSlice p M x time)
        (finiteNativeFirstJet p M
          (nativeCarryRealPlaneParameter sigma time)) sigma ∧
      HasDerivAt
        (fun y : ℝ => finiteNativeSlice p M sigma y)
        (Complex.I * finiteNativeFirstJet p M
          (nativeCarryRealPlaneParameter sigma time)) time ∧
      finiteNativeTimeTangent p M sigma time =
        nativeQuarterTurn
          (finiteNativeSigmaTangent p M sigma time) ∧
      nativePlaneInner
          (finiteNativeTimeTangent p M sigma time)
          (finiteNativeTimeTangent p M sigma time) =
        nativePlaneInner
          (finiteNativeSigmaTangent p M sigma time)
          (finiteNativeSigmaTangent p M sigma time) ∧
      nativePlaneInner
          (finiteNativeSigmaTangent p M sigma time)
          (finiteNativeTimeTangent p M sigma time) = 0 := by
  refine ⟨
    finiteNativeSlice_eq_packaged_realCamera p M hp hpodd sigma time,
    finiteNativeSlice_hasDerivAt_sigma p M hp sigma time,
    finiteNativeSlice_hasDerivAt_time p M hp sigma time,
    finiteNativeTimeTangent_eq_quarterTurn p M sigma time,
    ?_, ?_⟩
  · rw [finiteNativeTimeTangent_eq_quarterTurn]
    exact nativePlaneInner_quarterTurn_self _
  · rw [finiteNativeTimeTangent_eq_quarterTurn]
    exact nativePlaneInner_self_quarterTurn _

end

end GenuineZeroUniformAtlasEnergy
