import GenuineZeroUniformAtlasEnergy.NativeGeometry
import CPFormal.Analytic.CpGenuineCarryTiltFrontier

/-!
# The tilted center left after boundary telescoping

The coupled Green flux splits exactly into two independently defined pieces:

`total flux = centered bulk + coupled boundary`.

The centered bulk factors as the radial carry difference times a strictly
positive reflected pairing.  Therefore it vanishes exactly when the local
carry tilt vanishes, equivalently when the quadratic shell has no transverse
displacement.

At the common native/Genuine zero, the boundary telescopes.  The remaining
center is consequently the complete detector of radial imbalance.  On the
native positional wave the quadratic carry shell is already balanced, so both
the center and the total flux close.
-/

open scoped Topology

namespace GenuineZeroUniformAtlasEnergy

open Filter
open CPFormal.Analytic.Cp
open CPFormal.Genuine.Cp

noncomputable section

/-- The bulk remaining after subtracting the independently defined coupled
boundary from the total bracket-coupled Green flux. -/
def finiteTiltedCenter (p M : ℕ) (s : ℂ) : ℝ :=
  finiteBracketCoupledCpGreenFlux p M s -
    finiteBracketCoupledSignedBoundary M s

/-- Exact center factorization: the surviving bulk receives the radial factor
generated by the quadratic carry displacement. -/
theorem finiteTiltedCenter_eq_radialDifference_mul_pairing
    (p M : ℕ) (hp : Nat.Prime p) (s : ℂ) :
    finiteTiltedCenter p M s =
      cpRadialDifference p (criticalDisplacement s.re) *
        (finiteReflectedGradientPairing M s).re := by
  unfold finiteTiltedCenter
  rw [finiteBracketCoupledCpGreenFlux_eq_radialDifference_mul_pairing
    p M hp s]
  ring

/-- Direct critical-line detector: at every nonempty cutoff in the strip, the
surviving center vanishes exactly when the real coordinate is `1/2`. -/
theorem finiteTiltedCenter_eq_zero_iff_re_eq_half
    (p M : ℕ) (hp : Nat.Prime p) (hM : 0 < M)
    {s : ℂ} (hs : s ∈ genuineCriticalStrip) :
    finiteTiltedCenter p M s = 0 ↔ s.re = (1 : ℝ) / 2 := by
  have hpairing : 0 < (finiteReflectedGradientPairing M s).re :=
    finiteReflectedGradientPairing_re_pos hM hs
  rw [finiteTiltedCenter_eq_radialDifference_mul_pairing p M hp s]
  constructor
  · intro hzero
    have hradial :
        cpRadialDifference p (criticalDisplacement s.re) = 0 :=
      (mul_eq_zero.mp hzero).resolve_right (ne_of_gt hpairing)
    have hdelta :=
      (cpRadialDifference_eq_zero_iff
        p hp (criticalDisplacement s.re)).1 hradial
    unfold criticalDisplacement at hdelta
    linarith
  · intro hhalf
    simp [criticalDisplacement, hhalf, cpRadialDifference]

/-- At every nonempty cutoff in the strip, the tilted center vanishes exactly
when the carry tilt vanishes.  The positive pairing prevents cancellation from
hiding a nonzero transverse factor. -/
theorem finiteTiltedCenter_eq_zero_iff_carryTilt_eq_zero
    (p M : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (center : ℝ) (hcenter : (halfRange p : ℝ) < center)
    (hM : 0 < M) {s : ℂ} (hs : s ∈ genuineCriticalStrip) :
    finiteTiltedCenter p M s = 0 ↔
      cpTiltAtSigma p s.re center = 0 := by
  exact (finiteTiltedCenter_eq_zero_iff_re_eq_half p M hp hM hs).trans
    (cpTiltAtSigma_eq_zero_iff_half
      p hp hpodd hs.1 hcenter).symm

/-- Exact norm--tilt--center crosswalk: the surviving Green center vanishes
exactly when the quadratic branch-norm defect vanishes. -/
theorem finiteTiltedCenter_eq_zero_iff_quadraticBranchDefect_eq_zero
    (p M : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (center : ℝ) (hcenter : (halfRange p : ℝ) < center)
    (hM : 0 < M) {s : ℂ} (hs : s ∈ genuineCriticalStrip) :
    finiteTiltedCenter p M s = 0 ↔ branchDefect p s.re = 0 := by
  exact
    (finiteTiltedCenter_eq_zero_iff_carryTilt_eq_zero
      p M hp hpodd center hcenter hM hs).trans
      (branchDefect_eq_zero_iff_cpTiltAtSigma_eq_zero_of_admissible_center
        p hp hpodd hs.1 hcenter).symm

/-- Sign-sensitive form: a nonzero carry tilt is detected by a nonzero center
at every nonempty cutoff. -/
theorem finiteTiltedCenter_ne_zero_of_carryTilt_ne_zero
    (p M : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (center : ℝ) (hcenter : (halfRange p : ℝ) < center)
    (hM : 0 < M) {s : ℂ} (hs : s ∈ genuineCriticalStrip)
    (htilt : cpTiltAtSigma p s.re center ≠ 0) :
    finiteTiltedCenter p M s ≠ 0 :=
  (finiteTiltedCenter_eq_zero_iff_carryTilt_eq_zero
    p M hp hpodd center hcenter hM hs).not.mpr htilt

/-- Once the common-zero boundary telescopes, closing the total flux is
equivalent to annihilating the carry tilt.  This is the direct formal statement
that the surviving center detects departure from the quadratic shell. -/
theorem totalFlux_closes_iff_carryTilt_balanced_at_commonZero
    (p : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (center : ℝ) (hcenter : (halfRange p : ℝ) < center)
    {s : ℂ} (hs : s ∈ genuineCriticalStrip)
    (hzero : genuineContinuation s = 0) :
    Tendsto (fun M : ℕ ↦ finiteBracketCoupledCpGreenFlux p M s)
        atTop (nhds 0) ↔
      cpTiltAtSigma p s.re center = 0 := by
  rw [coupledFlux_tendsto_zero_iff_criticalDisplacement_eq_zero
      p hp hs hzero,
    cpTiltAtSigma_eq_zero_iff_half p hp hpodd hs.1 hcenter]
  unfold criticalDisplacement
  constructor <;> intro h <;> linarith

/-- Native capstone.  At the single zero shared by the native camera and the
Genuine notation, the boundary telescopes, the tilted center vanishes at every
cutoff, the carry tilt is balanced, and the total coupled flux closes. -/
theorem nativeGenuineZero_telescopes_boundary_and_balances_tiltedCenter
    (p : ℕ) (hp : Nat.Prime p) (hpodd : Odd p)
    (center : ℝ) (hcenter : (halfRange p : ℝ) < center)
    (time : ℝ)
    (hzero : NativeCarryRealOperatorBoundaryClosesAt
      3 ((1 : ℝ) / 2) time) :
    Tendsto
        (fun M : ℕ ↦
          finiteBracketCoupledSignedBoundary M (nativeParameter time))
        atTop (nhds 0) ∧
      (∀ M : ℕ, finiteTiltedCenter p M (nativeParameter time) = 0) ∧
      cpTiltAtSigma p (nativeParameter time).re center = 0 ∧
      branchDefect p (nativeParameter time).re = 0 ∧
      Tendsto
        (fun M : ℕ ↦
          finiteBracketCoupledCpGreenFlux p M (nativeParameter time))
        atTop (nhds 0) := by
  have hs := nativeParameter_mem_genuineCriticalStrip time
  have hgenuine : genuineContinuation (nativeParameter time) = 0 :=
    (nativeZero_iff_genuineZero time).1 hzero
  have hboundary :=
    finiteBracketCoupledSignedBoundary_tendsto_zero_of_genuine_zero
      hs hgenuine
  have hcenterZero :
      ∀ M : ℕ, finiteTiltedCenter p M (nativeParameter time) = 0 := by
    intro M
    rw [finiteTiltedCenter_eq_radialDifference_mul_pairing
      p M hp (nativeParameter time)]
    simp [criticalDisplacement, cpRadialDifference]
  have htilt :
      cpTiltAtSigma p (nativeParameter time).re center = 0 := by
    exact (cpTiltAtSigma_eq_zero_iff_half
      p hp hpodd hs.1 hcenter).2 (nativeParameter_re time)
  have hbranch : branchDefect p (nativeParameter time).re = 0 :=
    (finiteTiltedCenter_eq_zero_iff_quadraticBranchDefect_eq_zero
      p 1 hp hpodd center hcenter (by norm_num) hs).1 (hcenterZero 1)
  have hflux :
      Tendsto
        (fun M : ℕ ↦
          finiteBracketCoupledCpGreenFlux p M (nativeParameter time))
        atTop (nhds 0) :=
    (totalFlux_closes_iff_carryTilt_balanced_at_commonZero
      p hp hpodd center hcenter hs hgenuine).2 htilt
  exact ⟨hboundary, hcenterZero, htilt, hbranch, hflux⟩

end

end GenuineZeroUniformAtlasEnergy
